version: "3.9"
services:
  qme-config:
    environment:
      - USER=qmecfg
      - PORT=3010   
      - PGUSER=qmecfg         
      - PGPASSWORD=n0tS3cr3t!
      - PGDATABASE=qmecfg
      - PGHOST=qme-config-db
      - PGPORT=5432
    build: .
    ports:
      - "3010:3010"
  qme-config-db:
    image: postgres
    environment:
      - POSTGRES_USER=qmecfg
      - POSTGRES_PASSWORD=n0tS3cr3t!
    ports:
      - "5410:5432"
    volumes:
      - qme-config-db-volume:/var/lib/postgresql/data

volumes:
  qme-config-db-volume: