--CREATE USER qmecfg WITH PASSWORD 'qmecfgInitPwd1!';

--CREATE DATABASE qmessentials_configuration OWNER='qmecfg';

create table product (
    product_id varchar primary key,
    product_name varchar not null,
    product_status varchar not null,
    created_date timestamp with time zone not null,
    created_by_user_id varchar not null,
    last_updated_date timestamp with time zone not null,
    last_updated_by_user_id varchar not null
);

create table item (
    item_id varchar primary key,
    lot_info varchar not null,
    product_id varchar not null references product (product_id),
    item_status varchar not null,
    created_date timestamp with time zone not null,
    created_by_user_id varchar not null,
    last_updated_date timestamp with time zone not null,
    last_updated_by_user_id varchar not null
);

create table test (
    test_name varchar primary key,
    unit_type varchar not null,
    created_date timestamp with time zone not null,
    created_by_user_id varchar not null,
    last_updated_date timestamp with time zone not null,
    last_updated_by_user_id varchar not null
);

create table product_test_set (
    product_test_set_id integer primary key generated by default as identity,
    product_id varchar not null references product (product_id),
    usage_notes varchar null,
    created_date timestamp with time zone not null,
    created_by_user_id varchar not null,
    last_updated_date timestamp with time zone not null,
    last_updated_by_user_id varchar not null
);

create table product_test (
    product_test_set_id integer not null references product_test_set (product_test_set_id), 
    test_name varchar not null references test (test_name),
    sequence_number integer not null,
    unit varchar not null,
    min_value double precision null,
    max_value double precision  null,
    standards varchar[] null,
    document_references varchar[] null,
    created_date timestamp with time zone not null,
    created_by_user_id varchar not null,
    last_updated_date timestamp with time zone not null,
    last_updated_by_user_id varchar not null
);

    

